apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: https
  selector:
    app: deployment_b-dep2pod-label

